- type: replace
  path: /addons/name=metron_agent
  value:
    name: loggregator_agent
    include:
      stemcell:
      - os: ubuntu-trusty
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: loggregator_agent
      release: loggregator-agent
      properties:
        loggregator:
          tls:
            ca_cert: "((loggregator_ca.certificate))"
            agent:
              cert: "((loggregator_tls_metron.certificate))"
              key: "((loggregator_tls_metron.private_key))"

- type: replace
  path: /releases/-
  value:
    name: loggregator-agent
    version: latest
